# Grid World Environment

In [44]:
import numpy as np
import gymnasium as gym
from gymnasium import spaces

class GridWorldEnv(gym.Env):
    def __init__(self, grid_size, start, goal, obstacles):
        super(GridWorldEnv, self).__init__()
        self.grid_size = grid_size
        self.start = start
        self.goal = goal
        self.obstacles = obstacles
        self.action_space = spaces.Discrete(4)  # Four actions: up, down, left, right
        self.observation_space = spaces.Tuple((
            spaces.Discrete(grid_size[0]),
            spaces.Discrete(grid_size[1])
        ))
        self.reset()

    def reset(self):
        self.agent_pos = list(self.start)
        return tuple(self.agent_pos)

    def step(self, action):
        # Define actions: 0=up, 1=down, 2=left, 3=right
        if action == 0 and self.agent_pos[0] > 0:  # Up
            self.agent_pos[0] -= 1
        elif action == 1 and self.agent_pos[0] < self.grid_size[0] - 1:  # Down
            self.agent_pos[0] += 1
        elif action == 2 and self.agent_pos[1] > 0:  # Left
            self.agent_pos[1] -= 1
        elif action == 3 and self.agent_pos[1] < self.grid_size[1] - 1:  # Right
            self.agent_pos[1] += 1
        
        reward = -1
        done = False
        if tuple(self.agent_pos) == self.goal:
            reward = 10
            done = True
        elif tuple(self.agent_pos) in self.obstacles:
            reward = -10
            done = True

        return tuple(self.agent_pos), reward, done, {}

    def render(self, mode='human'):
        grid = np.zeros(self.grid_size)
        grid[self.start] = 1  # Start position
        grid[self.goal] = 2  # Goal position
        for obstacle in self.obstacles:
            grid[obstacle] = -1  # Obstacle positions
        grid[tuple(self.agent_pos)] = 3  # Agent position
        print(grid)

# Example usage
grid_size = (5, 5)
start = (0, 0)
goal = (4, 4)
obstacles = [(1, 1), (2, 2), (3, 3)]

env = GridWorldEnv(grid_size, start, goal, obstacles)
obs = env.reset()
env.render()

done = False
while not done:
    action = env.action_space.sample()
    obs, reward, done, _ = env.step(action)
    env.render()
    print(f"Action: {action}, Reward: {reward}")


[[ 3.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  2.]]
[[ 1.  0.  0.  0.  0.]
 [ 3. -1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  2.]]
Action: 1, Reward: -1
[[ 3.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  2.]]
Action: 0, Reward: -1
[[ 1.  0.  0.  0.  0.]
 [ 3. -1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  2.]]
Action: 1, Reward: -1
[[ 1.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [ 3.  0. -1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  2.]]
Action: 1, Reward: -1
[[ 1.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [ 3.  0. -1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  2.]]
Action: 2, Reward: -1
[[ 1.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [ 3.  0. -1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  2.]]
Action: 2, Reward: -1
[[ 1.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [ 0.  0. 

# Multi-Armed Bandit Environment

In [45]:
import numpy as np

class MultiArmedBanditEnv(gym.Env):
    def __init__(self, k_arms, reward_distributions):
        super(MultiArmedBanditEnv, self).__init__()
        self.k_arms = k_arms
        self.reward_distributions = reward_distributions
        self.action_space = spaces.Discrete(k_arms)
        self.observation_space = spaces.Discrete(1)
        self.reset()

    def reset(self):
        return 0  # Single-state problem

    def step(self, action):
        reward = np.random.normal(self.reward_distributions[action][0], self.reward_distributions[action][1])
        return 0, reward, False, {}  # Single-state, so always return state 0

# Example usage
k_arms = 10
reward_distributions = [(np.random.rand(), 1) for _ in range(k_arms)]

env = MultiArmedBanditEnv(k_arms, reward_distributions)
obs = env.reset()
for _ in range(100):
    action = env.action_space.sample()
    obs, reward, done, _ = env.step(action)
    print(f"Action: {action}, Reward: {reward}")


Action: 5, Reward: 0.40373590725149966
Action: 6, Reward: -1.5682592517119807
Action: 9, Reward: 1.7101819968807335
Action: 3, Reward: -0.02057601668038067
Action: 1, Reward: 0.8522818793842781
Action: 0, Reward: -0.6532468191367629
Action: 2, Reward: 0.8926445934082499
Action: 3, Reward: 2.5665910308669995
Action: 8, Reward: 0.3812166853629977
Action: 2, Reward: 0.5895597532453235
Action: 0, Reward: -1.535064337854422
Action: 6, Reward: -0.16983353715885718
Action: 6, Reward: -0.08292468759490379
Action: 6, Reward: -0.14443598378826272
Action: 4, Reward: -0.899093203150997
Action: 2, Reward: 1.6113902442569712
Action: 9, Reward: 0.4869177290045204
Action: 4, Reward: -0.18073610705549026
Action: 4, Reward: 0.26995636804059
Action: 5, Reward: 0.15240136142502553
Action: 8, Reward: 2.0155883483962693
Action: 2, Reward: 2.116799243819492
Action: 3, Reward: 0.6936743554941673
Action: 9, Reward: 0.3186059913055259
Action: 0, Reward: -1.2369020922824094
Action: 8, Reward: -0.3775663825754169

# Value Iteration

In [56]:
def value_iteration(env, gamma=0.99, theta=1e-6):
    n_states = env.observation_space[0].n * env.observation_space[1].n
    value_table = np.zeros(n_states)
    policy = np.zeros(n_states, dtype=int)

    while True:
        delta = 0
        for state in range(n_states):
            v = value_table[state]
            q_values = []
            for action in range(env.action_space.n):
                next_state, reward, done, _ = env.step(action)
                prob = 1  # deterministic environment
                q_values.append(prob * (reward + gamma * value_table[next_state[0] * env.grid_size[1] + next_state[1]]))
            value_table[state] = max(q_values)
            delta = max(delta, abs(v - value_table[state]))
        if delta < theta:
            break

    for state in range(n_states):
        q_values = []
        for action in range(env.action_space.n):
            next_state, reward, done, _ = env.step(action)
            prob = 1  # deterministic environment
            q_values.append(prob * (reward + gamma * value_table[next_state[0] * env.grid_size[1] + next_state[1]]))
        policy[state] = np.argmax(q_values)

    return policy, value_table


# Policy Iteration


In [47]:
def policy_iteration(env, gamma=0.99, theta=1e-6):
    n_states = env.observation_space[0].n * env.observation_space[1].n
    n_actions = env.action_space.n
    policy = np.random.choice(n_actions, n_states)
    value_table = np.zeros(n_states)

    def one_step_lookahead(state, value_table):
        action_values = np.zeros(n_actions)
        for action in range(n_actions):
            next_state, reward, done, _ = env.step(action)
            prob = 1  # deterministic environment
            next_state_index = next_state[0] * env.grid_size[1] + next_state[1]
            action_values[action] += prob * (reward + gamma * value_table[next_state_index])
        return action_values

    while True:
        # Policy Evaluation
        while True:
            delta = 0
            for state in range(n_states):
                v = value_table[state]
                action = policy[state]
                next_state, reward, done, _ = env.step(action)
                next_state_index = next_state[0] * env.grid_size[1] + next_state[1]
                value_table[state] = reward + gamma * value_table[next_state_index]
                delta = max(delta, abs(v - value_table[state]))
            if delta < theta:
                break

        # Policy Improvement
        policy_stable = True
        for state in range(n_states):
            chosen_action = policy[state]
            action_values = one_step_lookahead(state, value_table)
            best_action = np.argmax(action_values)
            if chosen_action != best_action:
                policy_stable = False
            policy[state] = best_action

        if policy_stable:
            break

    return policy, value_table


# Q-Learning

In [48]:
def q_learning(env, alpha=0.1, gamma=0.99, epsilon=0.1, episodes=1000):
    n_states = env.observation_space[0].n * env.observation_space[1].n
    n_actions = env.action_space.n
    q_table = np.zeros((n_states, n_actions))

    def choose_action(state):
        if np.random.uniform(0, 1) < epsilon:
            return np.random.choice(n_actions)
        else:
            return np.argmax(q_table[state, :])

    for _ in range(episodes):
        state = env.reset()
        state_index = state[0] * env.grid_size[1] + state[1]
        done = False
        while not done:
            action = choose_action(state_index)
            next_state, reward, done, _ = env.step(action)
            next_state_index = next_state[0] * env.grid_size[1] + next_state[1]
            q_table[state_index, action] += alpha * (reward + gamma * np.max(q_table[next_state_index, :]) - q_table[state_index, action])
            state_index = next_state_index

    policy = np.argmax(q_table, axis=1)
    return policy, q_table


# Epsilon-Greedy Policy for Multi-Armed Bandit

In [49]:
def epsilon_greedy_bandit(env, alpha=0.1, epsilon=0.1, episodes=1000):
    q_values = np.zeros(env.action_space.n)
    action_counts = np.zeros(env.action_space.n)

    for _ in range(episodes):
        if np.random.uniform(0, 1) < epsilon:
            action = np.random.choice(env.action_space.n)
        else:
            action = np.argmax(q_values)

        _, reward, _, _ = env.step(action)
        action_counts[action] += 1
        q_values[action] += (reward - q_values[action]) / action_counts[action]

    return q_values


# Upper Confidence Bound (UCB) Algorithm for Multi-Armed Bandit

In [50]:
def ucb_bandit(env, alpha=0.1, episodes=1000):
    q_values = np.zeros(env.action_space.n)
    action_counts = np.zeros(env.action_space.n)
    total_steps = 0

    for _ in range(episodes):
        total_steps += 1
        ucb_values = q_values + np.sqrt(2 * np.log(total_steps) / (action_counts + 1e-5))
        action = np.argmax(ucb_values)

        _, reward, _, _ = env.step(action)
        action_counts[action] += 1
        q_values[action] += (reward - q_values[action]) / action_counts[action]

    return q_values


In [51]:
def test_grid_world_algorithms():
    # Define the Grid World environment
    grid_size = (5, 5)
    start = (0, 0)
    goal = (4, 4)
    obstacles = [(1, 1), (2, 2), (3, 3)]
    
    env = GridWorldEnv(grid_size, start, goal, obstacles)

    # Test Value Iteration
    print("Testing Value Iteration...")
    policy, value_table = value_iteration(env)
    print("Optimal Policy (Value Iteration):")
    print(policy.reshape(grid_size))
    print("Value Table (Value Iteration):")
    print(value_table.reshape(grid_size))
    print()

    # Test Policy Iteration
    print("Testing Policy Iteration...")
    policy, value_table = policy_iteration(env)
    print("Optimal Policy (Policy Iteration):")
    print(policy.reshape(grid_size))
    print("Value Table (Policy Iteration):")
    print(value_table.reshape(grid_size))
    print()

    # Test Q-Learning
    print("Testing Q-Learning...")
    policy, q_table = q_learning(env)
    print("Optimal Policy (Q-Learning):")
    print(policy.reshape(grid_size))
    print("Q-Table (Q-Learning):")
    print(q_table.reshape(grid_size[0], grid_size[1], -1))
    print()

# Run the test function
test_grid_world_algorithms()


Testing Value Iteration...
Optimal Policy (Value Iteration):
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Value Table (Value Iteration):
[[-99.99990137 -99.99990137 -99.99990137 -99.99990137 -99.99990137]
 [-99.99990137 -99.99990235 -99.99990235 -99.99990235 -99.99990235]
 [-99.99990235 -99.99990235 -99.99990235 -99.99990235 -99.99990235]
 [-99.99990235 -99.99990235 -99.99990235 -99.99990235 -99.99990235]
 [-99.99990235 -99.99990235 -99.99990235 -99.99990235 -99.99990235]]

Testing Policy Iteration...
Optimal Policy (Policy Iteration):
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Value Table (Policy Iteration):
[[-100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100.]]

Testing Q-Learning...
Optimal Policy (Q-Learning):
[[3 3 3 1 1]
 [1 0 3 3 1]
 [3 1 0 3 1]
 [3 3 1 0 1]
 [3 3 3 3 0]]
Q-Table (Q-Learning):
[[[ 0.83677743 -2.78965913  0.575

In [52]:
def test_multi_armed_bandit_algorithms():
    # Define the Multi-Armed Bandit environment
    k_arms = 10
    reward_distributions = [(np.random.rand(), 1) for _ in range(k_arms)]
    
    env = MultiArmedBanditEnv(k_arms, reward_distributions)

    # Test Epsilon-Greedy Policy
    print("Testing Epsilon-Greedy Policy...")
    q_values = epsilon_greedy_bandit(env)
    print("Estimated Q-Values (Epsilon-Greedy):")
    print(q_values)
    print()

    # Test UCB Algorithm
    print("Testing UCB Algorithm...")
    q_values = ucb_bandit(env)
    print("Estimated Q-Values (UCB):")
    print(q_values)
    print()

# Run the test function
test_multi_armed_bandit_algorithms()


Testing Epsilon-Greedy Policy...
Estimated Q-Values (Epsilon-Greedy):
[ 0.65966084  0.47458021  0.838381   -0.03847589 -0.00824702  0.50346637
  0.65733079  0.88689306 -0.05956219  0.63702932]

Testing UCB Algorithm...
Estimated Q-Values (UCB):
[ 0.77913778 -0.81935112  0.81188003  0.41120405  0.40738414  0.30022621
  0.25672315  0.90441666  0.20479527  0.10894806]



In [57]:
def main():
    print("===== Testing Grid World Algorithms =====")
    test_grid_world_algorithms()
    
    print("===== Testing Multi-Armed Bandit Algorithms =====")
    test_multi_armed_bandit_algorithms()

if __name__ == "__main__":
    main()


===== Testing Grid World Algorithms =====
Testing Value Iteration...
Optimal Policy (Value Iteration):
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Value Table (Value Iteration):
[[-99.99990137 -99.99990137 -99.99990137 -99.99990137 -99.99990137]
 [-99.99990137 -99.99990235 -99.99990235 -99.99990235 -99.99990235]
 [-99.99990235 -99.99990235 -99.99990235 -99.99990235 -99.99990235]
 [-99.99990235 -99.99990235 -99.99990235 -99.99990235 -99.99990235]
 [-99.99990235 -99.99990235 -99.99990235 -99.99990235 -99.99990235]]

Testing Policy Iteration...
Optimal Policy (Policy Iteration):
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Value Table (Policy Iteration):
[[-99.9999908  -99.9999908  -99.99999089 -99.99999089 -99.99999089]
 [-99.99999089 -99.99999089 -99.99999089 -99.99999089 -99.99999089]
 [-99.99999089 -99.99999089 -99.99999089 -99.99999089 -99.99999089]
 [-99.99999089 -99.99999089 -99.99999089 -99.99999089 -99.99999089]
 [-99.99999089 -99.999990